#  docker-compose -f mongo.yml build
version: '3.5'
services:
  rabbitmq:
    build: docker/mongodb
    environment:
      TERM: dotalk
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data:/data/db
    restart: always
    container_name: l-mongo
    networks:
      - backend
networks:
  backend: