version: '3.5'
services:
  php:
    build: ./docker/php/7.2.3-fpm-debian
#    volumes:
#      - ./php/conf/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
#      - ./php/conf/docker.conf:/usr/local/etc/php-fpm.d/docker.conf
#      - ./php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
#      - ./run:/var/run/
#      - ./www:/var/www/html
    networks:
      - frontend
    environment:
      DOTALK_X: yongze.chen
    restart: always
    container_name: l-php-test-723-1
networks:
  frontend: