version: '2'
services:
  python:
    build: ./docker/python/3.8.0a3-alpine3.9
    ports:
      - "8189:5000"
    volumes:
      - ./docker/python/3.8.0a3-alpine3.9/app:/app
    depends_on:
      - redis
    container_name: flask-web
  redis:
    build: ./docker/redis/redis-latest
    volumes:
      - ./docker/redis/redis-latest/conf/redis.conf:/usr/local/etc/redis.conf
      - ./docker/redis/redis-latest/data:/usr/local/redis/data
      - ./docker/redis/redis-latest/redis.log:/usr/local/redis/redis.log
    container_name: redis-b-9